### ISSUE TITLE
Fallimento della logica di divisione in sezioni

### ISSUE THREAD

**Issue by danse** [italia/pandoc-docs2rst#12]
Il documento `input.docx` qui https://github.com/pablopers/pianoprevecorr è molto lungo e vorremmo che la divisione in sezioni funzionasse risparmiando tempo a @pablopers ma sembra non funzionare

**Comment by danse** [comment]
ah, @pablopers ho capito perché il tuo documento non è stato diviso automaticamente in sezioni! Tutti i titoli nel documento sono in grassetto, non sono formattati come headers Word. Si tratterebbe di modificarli tutti a mano e convertirli in headers, ma posso scriverti un filtro che lo faccia automaticamente

**Comment by pablopers** [comment]
facciamolo subito! :-)

**Comment by danse** [comment]
aspetta in realtà i numeri potrebbero aiutarci a dedurre la struttura del documento, giusto? che intendi per interruzioni di pagina? non ce ne sono in RST

**Comment by pablopers** [comment]
> i numeri potrebbero aiutarci a dedurre la struttura del documento, giusto?
penso di no! in quanto la struttura nella conversione da pdf a doc (o docx) cambia e accade che le interruzioni di pagina naturali nel documento originale vengano riportati nel documento convertito così: 

![interruzione di pagina](https://user-images.githubusercontent.com/36224887/40716529-9966b598-6409-11e8-980c-7740b65afffd.jpg)

> che intendi per interruzioni di pagina?
in sostanza un salto del contenuto nella pagina successiva

**Comment by danse** [comment]
capisco quindi questi numeri sono numeri di pagina di cui vogliamo liberarci. questo dovrebbe essere possibile perché hanno una struttura strana ... sono numeri interi che stanno da soli in un paragrafo  ... `Para [Str "2"]` nel documento `.native`. Come hai convertito questo PDF? Lo stesso problema potrebbe succedere ad altri utenti che convertano alla stessa maniera

**Comment by pablopers** [comment]
google drive + Google docs (utile anche perché accessibile a tutti senza installazioni etc). 
Intanto sto provando ad arricchire il file da 193 pagine con tabelle e immagini.

**Comment by danse** [comment]
le tabelle ed immagini sono molte? in quel caso puoi provare l'altro metodo, dalla guida. Credo che sarebbe anche figo integrare le vostre idee nella guida

**Comment by danse** [comment]
magari potrebbe essere la prima pull request di modifica della guida :)

**Comment by danse** [comment]
ho scritto il filtro, da buoni risultati nel caso di `newfoia`. qui c'è il codice del filtro che come vedi è molto semplice https://github.com/italia/pandoc-filters/blob/master/filters/bold-headers.hs, qui la descrizione https://github.com/italia/pandoc-filters/tree/master/filters#bold-headershs

**Comment by danse** [comment]
ho anche scritto un filtro che rimuove i numeri di pagina da `pianoprevecorr` e sembra funzionare bene, potremo applicarlo dopo che avrai fatto con immagini e tabelle

**Comment by danse** [comment]
questo non era un fallimento della logica in realtà, però ci ha aiutato a produrre due filtri molto utili ... grazie per la segnalazione!
