### ISSUE TITLE
Alt text e didascalia

### ISSUE THREAD

**Issue by atorin** [italia/pandoc-docs2rst#5]
Questo [documento di test](https://github.com/italia/pandoc-docs2rst/blob/master/input/test/caption.docx) contiene un'immagine con didascalia e testo alternativo. 

- Il testo alternativo viene inserito come segnaposto nel file RST, invece che nel comando `:alt:`
- La didascalia viene convertita come testo, invece che nel comando `:caption:`

In aggiunta, il titolo non viene convertito per niente.

**Comment by danse** [comment]
il problema del titolo mi sembra più grave quindi comincerò da quello

**Comment by danse** [comment]
questo riguarda il titolo https://github.com/jgm/pandoc/issues/4583

**Comment by danse** [comment]
ricordo che questo problema del titolo si era già verificato. La soluzione è di usare l'opzione `-s`, anche se non è molto intuitivo; dell'usabilità si è discusso nella issue collegata sopra. ho aggiunto l'opzione agli script e nella guida https://github.com/italia/pandoc-docs2rst/blob/master/guida.md#opzioni

**Comment by danse** [comment]
ricapitolando:
- il titolo viene inserito usando l'opzione `-s` di pandoc, aggiunta in `pandoc-docs2rst` e nella relativa guida
- sull'alt text non siamo pienamente soddisfatti ma il risultato nell'HTML va bene
- la didascalia non veniva aggiunta, per questo abbiamo aggiunto il filtro `figure` in `pandoc-filters` che viene usato automaticamente in `pandoc-docs2rst`

alcuni utenti potrebbero inserire una didascalia in modo tale che non venga convertita dal nostro filtro, [questa carta trello](https://trello.com/c/dpDoPdgz/224-come-tech-writer-vorrei-non-dovermi-preoccupare-del-metodo-da-seguire-per-inserire-una-didascalia) è dedicata a quel caso
