### ISSUE TITLE
differente risultato di conversione

### ISSUE THREAD

**Issue by danse** [italia/pandoc-docs2rst#9]
@atorin ha riscontrato delle differenze che sono segnalate qui https://github.com/italia/pandoc-docs2rst/pull/8/files

**Comment by danse** [comment]
@atorin la prima differenza è che il linker alla normativa non è attivo nella tua installazione. ho aggiunto una nota al README a proposito di questo, trovi tutto nella pull request sul README

**Comment by danse** [comment]
non so ancora se il linker funzionerà su Mac, non so se hai provato ad installarlo, se ne parla qui https://github.com/italia/pandoc-docs2rst#collegamenti-automatici-alla-normativa

**Comment by atorin** [comment]
come ti ho segnalato nella PR, ho provato a installare lo script per i link alla normativa, ma lo zip che ho scaricato contiene un exe... o_0

**Comment by danse** [comment]
a parte le differenze dovute al linker normattiva, la tua versione delle conversioni ha rivelato limiti in `convert-docs-italia` e nel linker per la normattiva. ho preso nota su trello ed altrove. chiudo questa, ma è stata molto utile grazie 👍
